Argentina/Argentina/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

Argentina/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('messi/', views.messi, name='messi'),
    path('maradona/', views.maradona, name='maradona'),
    path('chi/givara/', views.chi_givara, name='chi_givara'),
    path('wc/history/', views.wc_history, name='wc_history'),
    path('argentina/history/', views.argentina_history, name='argentina_history'),
]

BlogWeb/BlogWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls"))
]

BlogWeb/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.home_view, name="home_view"),
    path("contactUs/", views.contactUs_view,  name= "contactUs_view"),
    path("login/", views.logIn_view,  name= "logIn_view"),
    path("singup/", views.singUp_view,  name= "singUp_view"),
]

Books_shop/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('',views.home, name = 'home'),
    path('contact/us/',views.contact_us, name = 'contact_us'),
]

GameStore/GameStore/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('main.urls'))
]

GameStore/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
  path("", views.home_view, name="home_view"),
  path("/about", views.about_view, name="about_view"),
  path("/contact", views.contact_view, name="contact_view")
]

MiniProject/main/urls.py
from . import views
from django.urls import path

#app_name = 'main'


urlpatterns = [
    path('', views.home_view, name= 'home'),
    path('contact/', views.contact_view, name='contact'),
]

MyProject/MyProject/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('', include("main.urls")),


]

MyProject/main/urls.py
from django.urls import path
from . import views
app_name ="main"
urlpatterns=[
    path('', views.movies_page, name='movies_page'),
    path('FantasticMrFox/',views.FantasticMrFox,name='FantasticMrFox'),
    path('spiritedAway/',views.spiritedAway,name='spiritedAway'),
    path('Coco/',views.Coco,name='Coco'),
    path('It_2017/',views.It_2017,name='It_2017'),
    path('split/',views.split,name='split'),

]

Practice_Lab/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    
]

QuizApp/QuizApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("quiz.urls"))
]

Tutorial/Tutorial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #path("admin/", admin.site.urls),
    path('', include("main.urls"))
]

Tutorial/main/urls.py
from . import views
from django.urls import path

app_name = 'main'


urlpatterns = [
    path('', views.home_view, name= 'home'),

]

TuwaiqLibrary/store/urls.py
from django.urls import path
from . import views

app_name = "store"

urlpatterns = [
    path('',views.home_page,name='home_page')

]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('/cosmic_mysteries', views.cosmic_mysteries, name='cosmic_mysteries'),
]

library/Book_list/urls.py
from django.urls import path
from . import views

name_app='Book_list'


urlpatterns = [
    path('',views.index , name='home_page'),
    path('CV',views.cv , name='home_page'),
]

library/library/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Book_list.urls")),
]

mysite/myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('services/', views.services, name='services'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

pet_store/pet_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]

pet_store/shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('cats/', views.cat_page, name='cat_page'),
    path('dogs/', views.dog_page, name='dog_page'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.view_cart, name='view_cart'),
    path('update_cart/', views.update_cart, name='update_cart'),
]

webPages/main/urls.py
from django.urls import path
from . import views
app_name = "main"
urlpatterns = [
    path('',views.home_views,name="home_views"),
    path('mini1/',views.mini1_views,name="mini1_views"),
    path('mini2/',views.mini2_views,name="mini2_views"),
    path("final/project/",views.final_views,name="final_views")
]

webPages/webPages/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include("main.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

Books_shop/books/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

# Create your views here.
def home(request: HttpRequest):

    return render(request, "books/home.html")



def contact_us(request: HttpRequest):

    return render(request, 'books/contact_us.html')

Books_shop/books/templates/books/contact_us.html
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <link rel="stylesheet" type="text/css" href="/static/css/style2.css">
    <title>تواصل معنا</title>
</head>
<body>
    <div class="container">
        <h1>تواصل معنا</h1>
        <form action="#">
            <label for="name">الاسم:</label>
            <input type="text" id="name" name="name" required>
            
            <label for="email">البريد الإلكتروني:</label>
            <input type="email" id="email" name="email" required>
            
            <label for="message">الرسالة:</label>
            <textarea id="message" name="message" rows="4" required></textarea>
            
            <button type="submit">إرسال</button>
        </form>
        
        <a href="{% url 'books:home' %}" class="goback">العودة إلى الصفحة الرئيسية</a>
    </div>
</body>
</html>

Books_shop/books/templates/books/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="static/css/style1.css">
    <title>My Bookstore</title>
</head>
<body>
    <div class="main-header">
        <div class="header">
            <img id="header-image" src="static/images/header.jpg" alt="Header Image">
            <div id="menu-header">
                <div id="menu">
                    <a href="#" class="btn active">الرئيسية</a>
                    <a href="#" class="btn">الكتب</a>
                    <a href="#" class="btn">التقييم</a>
                    <a href="#" class="btn">مقالات</a>
                    <a href="{% url 'books:contact_us' %}" class="btn">تواصل معنا</a>
                </div>
            </div>
        </div>
        <div id="main-content">
            <div id="centered-content">
                <h1>عالم الكتب</h1>
                <div id="img-frame">
                    <img src="static/images/logo.jpg" alt="Bookstore Logo">
                </div>
            </div>
        </div>
    </div>
</body>
</html>






<!-- 
<html>
    <head>
        <style>
            body{
                margin: 0;
            }
            .header{
                width:100%;
                height: 460px;
                background-color: red;
                overflow: hidden;

            }
            .header-image{
                width: 100%;
                position: relative;
                bottom:350;  
            
            }
            .header img{
            width: 100%;   
        }
        #menu-header{   
            width: 100%;
            height: 50px;
            position: absolute;
            top: 0;
            direction: rtl;
        }
        #menu{
            margin-right: 10px;
            margin-top: 20px;
        }
        #menu > .btn{
            margin-right: 30px;
            color: rgb(49, 2, 85);
            text-decoration:none;
            padding: 5p;
            border-radius: 10px;
            transition: background 0.3s;
        }

        #menu > .btn:hover{
            margin-right: 30px;
            color: rgb(126, 219, 5);
            text-decoration:none;
        }
        .active{
            background-color: coral;
            
        }
        #main-content{
            position: relative;
            width: 100%;
            background-color:green;
            display: flex;
            align-items: center;
            justify-content: center;
            height: calc(100vh - 460px); /*/////////8*/

        }
        #img-frame{
            height: 200px;
            width: 200px;
            padding: 10px;
            display: flex;
            justify-content: center;
            align-items: center;
            background-color:greenyellow;
            border-radius: 50%;
            margin: 0 auto;
            box-shadow: 0px 9px 8px rgb(204, 187, 187);
            transition: box-shadow  0.2s;
        }
        img-frame > img{
            height: 100%;
            width: 100%;
            object-fit: cover;   /*///////////////*/
        }
        img-frame:hover{
            box-shadow: 0px 9px 8px rgb(204, 187, 187);
            padding: 15px;
        }
        #centered-content{
            text-align: center;
            color:red
        }
        </style>
        <title>My Bookstore</title>
    </head>
    <body>
        <div class="main-header">
            <div class="header">
                <img id="header-image" src="static/images/header.jpg" alt="">
                <div id="menu-header">
                    <div id="menu">
                        <a href="#" class = 'btn active'>الرئيسية</a>
                        <a href="#" class = 'btn'>الكتب</a>
                        <a href="#" class = 'btn'>التقييم</a>
                        <a href="#" class = 'btn'>مقالات</a>
                        <a href="#" class = 'btn'>تواصل معنا</a>
                    </div>
                </div>
            </div>
            <div id="main-content">
                <div id="centered-content">
                    <h1>عالم الكتب</h1>
                    <div id="img-frame">
                        <img src="static/images/logo.jpg" alt="">
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>  -->